name: Run Sentiment Analysis

on:
  workflow_dispatch:  # Enables manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Runs the workflow every 6 hours
    # - cron: '*/1 * * * *'  # Runs the workflow every minute

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # Checks the python code from the repo

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install supabase pandas vaderSentiment  # Directly install dependencies without a requirements file

    - name: Run Sentiment Analysis Script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python sentiment_analysis.py
